version: "3"

services:
  frontend:
    # image: webpack
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      # - .:/app:cached
      # - /app/node_modules
      # - node_modules:/app/node_modules
      - /app/node_modules
      - node_modules:/app/node_modules
      # - .:/usr/src/app
      # - node_modules:/usr/src/app/node_modules

volumes:
  node_modules:
